// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDelP-a_eqvDhVryWZd0RqrPn_FuTNGwr4',
    appId: '1:143935591882:web:6c02ae7c64a39da6e6ab33',
    messagingSenderId: '143935591882',
    projectId: 'vanta-app-e98c5',
    authDomain: 'vanta-app-e98c5.firebaseapp.com',
    storageBucket: 'vanta-app-e98c5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa0C3EQob6ooezJGrcRLBLLOhwRd9g14I',
    appId: '1:143935591882:android:d6819284a4e7e961e6ab33',
    messagingSenderId: '143935591882',
    projectId: 'vanta-app-e98c5',
    storageBucket: 'vanta-app-e98c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuk4VZBVjD4RlTAnwBAYdL6LiNcrRJBEk',
    appId: '1:143935591882:ios:5fe6117659113800e6ab33',
    messagingSenderId: '143935591882',
    projectId: 'vanta-app-e98c5',
    storageBucket: 'vanta-app-e98c5.firebasestorage.app',
    androidClientId: '143935591882-40klultuffesme8unel5d9ev8fhrhb6v.apps.googleusercontent.com',
    iosClientId: '143935591882-l21vmk764hi6ld9bgle9se6vsnpmja2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.vantaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuk4VZBVjD4RlTAnwBAYdL6LiNcrRJBEk',
    appId: '1:143935591882:ios:5fe6117659113800e6ab33',
    messagingSenderId: '143935591882',
    projectId: 'vanta-app-e98c5',
    storageBucket: 'vanta-app-e98c5.firebasestorage.app',
    androidClientId: '143935591882-40klultuffesme8unel5d9ev8fhrhb6v.apps.googleusercontent.com',
    iosClientId: '143935591882-l21vmk764hi6ld9bgle9se6vsnpmja2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.vantaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDelP-a_eqvDhVryWZd0RqrPn_FuTNGwr4',
    appId: '1:143935591882:web:50369465119a92c1e6ab33',
    messagingSenderId: '143935591882',
    projectId: 'vanta-app-e98c5',
    authDomain: 'vanta-app-e98c5.firebaseapp.com',
    storageBucket: 'vanta-app-e98c5.firebasestorage.app',
  );
}
